<?php require __DIR__.'/../includes/admin.php';require_admin();
$s=$_GET['s']??'pages';$cats=cats_all();$pg=pages_all();$sp=species_all();$msgs=array_reverse(read_jsonl('messages'),true);$mem=read_jsonl('members');
$up=glob(ROOT.'/assets/uploads/*.*')?:[];$cnt=array_count_values(array_column($pg,'cat'));
$tabs=['pages'=>['📄','စာမျက်နှာများ'],'cats'=>['🗂️','အမျိုးအစားများ'],'species'=>['🐟','ငါးမျိုးစိတ်'],'msgs'=>['✉️','စာများ'],'members'=>['👥','စာရင်းသွင်းသူများ'],'media'=>['🖼️','ပုံများ'],'settings'=>['⚙️','Settings']];
?><!doctype html><html lang="my"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex">
<meta name="csrf" content="<?=h(admin_csrf())?>"><meta name="base" content="../"><title>Dashboard | Ayar Fish Farming</title>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Myanmar:wght@400;500;600;700&family=Noto+Serif+Myanmar:wght@600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../assets/css/site.css"><link rel="stylesheet" href="../assets/css/admin.css"><script src="../assets/js/admin.js" defer></script>
<script>window.APAGES=<?=json_encode(array_values(array_map(fn($d)=>[($d['label']??'')?:$d['title'],page_url($d)],$pg)),JSON_UNESCAPED_UNICODE)?>;window.ACATS=<?=json_encode(array_map(fn($c)=>[$c['id'],$c['icon'].' '.$c['title']],$cats),JSON_UNESCAPED_UNICODE)?>;window.SSPECIES=<?=json_encode(array_values($sp),JSON_UNESCAPED_UNICODE)?>;</script></head>
<body class="dash"><aside class="side"><a class="brand" href="../index.php"><img src="../assets/img/fish-logo.svg" alt=""><span>Ayar<small>ADMIN</small></span></a>
<nav><?php foreach($tabs as $k=>$t):?><a href="?s=<?=$k?>"<?=$s===$k?' class="on"':''?>><span><?=$t[0]?></span><?=h($t[1])?><?php if($k==='msgs'&&$msgs):?><em><?=count($msgs)?></em><?php endif;?></a><?php endforeach;?></nav>
<a class="vw" href="../index.php">🌐 Website ကို ကြည့်ပြီး ပြင်မည်</a><a class="lo" href="logout.php">Logout</a></aside>
<main class="dmain"><div class="dtop"><h1><?=$tabs[$s][0]??''?> <?=h($tabs[$s][1]??'')?></h1>
<?php if($s==='pages'):?><button class="btn" data-a="page-new">＋ စာမျက်နှာအသစ်</button><?php elseif($s==='cats'):?><button class="btn" data-a="cat-edit" data-row="{}">＋ အမျိုးအစားအသစ်</button><?php elseif($s==='species'):?><button class="btn" data-a="sp-edit" data-row="{}">＋ ငါးမျိုးစိတ်အသစ်</button><?php elseif($s==='media'):?><label class="btn">＋ ပုံတင်မည်<input type="file" accept="image/*" hidden data-a="media-up"></label><?php endif;?></div>
<?php if($s==='pages'):?>
<div class="stats"><div><b><?=count($pg)?></b>စာမျက်နှာ</div><div><b><?=count($cats)?></b>အမျိုးအစား</div><div><b><?=count($sp)?></b>ငါးမျိုးစိတ်</div><div><b><?=count($msgs)?></b>ရောက်လာသောစာ</div></div>
<?php foreach(array_merge($cats,[['id'=>'','icon'=>'📎','title'=>'မီနူးထဲမပါသော စာမျက်နှာများ']]) as $c):$g=array_filter($pg,fn($d)=>($d['cat']??'')===$c['id']);if(!$g&&$c['id']==='')continue;usort($g,fn($a,$b)=>($a['order']??0)<=>($b['order']??0));?>
<section class="card2"><h2><?=$c['icon']?> <?=h($c['title'])?> <small><?=count($g)?></small></h2><table><?php foreach($g as $d):$u=page_url($d);?><tr><td class="t"><a href="../<?=h($u.(strpos($u,'?')?'&':'?').'edit=1')?>"><?=h(($d['label']??'')?:$d['title'])?></a><small><?=h($u)?><?=!empty($d['updated'])?' · '.date('Y-m-d H:i',$d['updated']):''?></small></td>
<td class="ac"><button title="အပေါ်" data-a="page-move" data-id="<?=h($d['slug'])?>" data-d="-1">▲</button><button title="အောက်" data-a="page-move" data-id="<?=h($d['slug'])?>" data-d="1">▼</button><a class="ib" title="ကြည့်မည်" href="../<?=h($u)?>">👁</a><a class="ib" title="ပြင်မည်" href="../<?=h($u.(strpos($u,'?')?'&':'?').'edit=1')?>">✏️</a><?php if(empty($d['url'])):?><button title="ဖျက်မည်" data-a="page-del" data-id="<?=h($d['slug'])?>">🗑</button><?php endif;?></td></tr><?php endforeach;?></table></section><?php endforeach;?>
<?php elseif($s==='cats'):?><section class="card2"><table><?php foreach($cats as $c):?><tr><td class="t"><span class="big"><?=h($c['icon'])?></span> <b><?=h($c['title'])?></b><small><?=h($c['desc'])?> · စာမျက်နှာ <?=$cnt[$c['id']]??0?> ခု</small></td><td class="ac"><button data-a="cat-move" data-id="<?=h($c['id'])?>" data-d="-1">▲</button><button data-a="cat-move" data-id="<?=h($c['id'])?>" data-d="1">▼</button><button data-a="cat-edit" data-row="<?=h(json_encode($c,JSON_UNESCAPED_UNICODE))?>">✏️</button><button data-a="cat-del" data-id="<?=h($c['id'])?>">🗑</button></td></tr><?php endforeach;?></table></section>
<?php elseif($s==='species'):?><section class="card2"><table><?php foreach($sp as $x):?><tr><td class="t"><?php if(!empty($x['img'])):?><img class="th" src="../<?=h($x['img'])?>" alt=""><?php endif;?><b><?=h($x['name'])?></b><small><?=h($x['en'])?> · <em><?=h($x['sci'])?></em></small></td><td class="ac"><button data-a="sp-move" data-id="<?=h($x['id'])?>" data-d="-1">▲</button><button data-a="sp-move" data-id="<?=h($x['id'])?>" data-d="1">▼</button><button data-a="sp-edit" data-row="<?=h(json_encode($x,JSON_UNESCAPED_UNICODE))?>">✏️</button><button data-a="sp-del" data-id="<?=h($x['id'])?>">🗑</button></td></tr><?php endforeach;?></table></section>
<?php elseif($s==='msgs'):?><?php if(!$msgs):?><p class="empty">ရောက်လာသော စာ မရှိသေးပါ။</p><?php endif;foreach($msgs as $i=>$m):?><section class="card2 msg"><div class="mh"><b><?=h($m['name']??'')?></b><small><?=h($m['time']??'')?></small><button data-a="msg-del" data-file="messages" data-idx="<?=$i?>">🗑</button></div><p><?=nl2br(h($m['message']??''))?></p><small><?=h($m['phone']??'')?> <?=h($m['email']??'')?></small></section><?php endforeach;?>
<?php elseif($s==='members'):?><?php if(!$mem):?><p class="empty">စာရင်းသွင်းသူ မရှိသေးပါ။</p><?php else:?><section class="card2"><table><?php foreach($mem as $i=>$m):?><tr><td class="t"><b><?=h($m['name']??'')?></b><small><?=h($m['email']??'')?> · <?=h($m['phone']??'')?> · <?=h($m['address']??'')?></small></td><td class="ac"><button data-a="msg-del" data-file="members" data-idx="<?=$i?>">🗑</button></td></tr><?php endforeach;?></table></section><?php endif;?>
<?php elseif($s==='media'):?><?php if(!$up):?><p class="empty">တင်ထားသော ပုံ မရှိသေးပါ။ ပုံကို စာမျက်နှာထဲတွင် တိုက်ရိုက်ထည့်နိုင်ပါသည်။</p><?php endif;?><div class="mg"><?php foreach($up as $f):$n=basename($f);?><figure><img src="../assets/uploads/<?=h($n)?>" alt="" loading="lazy"><figcaption><button data-a="media-copy" data-url="assets/uploads/<?=h($n)?>">Copy URL</button><button data-a="media-del" data-name="<?=h($n)?>">🗑</button></figcaption></figure><?php endforeach;?></div>
<?php else:?><form class="form wide" id="sf"><h2>ဆက်သွယ်ရန်အချက်အလက်</h2><p class="hint">Website ၏ ဆက်သွယ်ရန် စာမျက်နှာတွင် ပြပါမည်။ စာသားများကို Website ပေါ်တွင် တိုက်ရိုက်လည်း ပြင်နိုင်ပါသည်။</p>
<?php foreach($LABELS as $k=>$l):$v=S($k,$DEF[$k]??$DEF_IMG[$k]??'');?><label><?=h($l)?></label><?php if(isset($DEF_IMG[$k])):?><div class="imgf"><input name="<?=h($k)?>" value="<?=h($v)?>" placeholder="assets/... သို့မဟုတ် https://"><?php if($v!==''):?><img src="../<?=h($v)?>" style="height:40px;border-radius:6px" alt=""><?php endif;?></div><?php else:?><input name="<?=h($k)?>" value="<?=h($v)?>"><?php endif;?><?php endforeach;?>
<button class="btn" type="button" data-a="settings-save">သိမ်းမည်</button></form>
<form class="form wide" id="pf"><h2>စကားဝှက် ပြောင်းရန်</h2><label>လက်ရှိ စကားဝှက်</label><input name="cur" type="password" autocomplete="current-password"><label>စကားဝှက်အသစ် (၈ လုံးအထက်)</label><input name="new" type="password" autocomplete="new-password"><button class="btn" type="button" data-a="pw-save">ပြောင်းမည်</button></form>
<?php endif;?></main></body></html>
